inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - vendor/**/*
  ExtraDetails: true
  TargetRubyVersion: 2.3

# Lints

# Metrics

Metrics/LineLength:
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "apps/*/application.rb"
    - "spec/**/*.rb"

# Style

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
